services:
  travel-agency-db:
    image: postgres:14
    container_name: travel-agency-db
    volumes:
      - travel-agency-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  travel-agency-test-db:
    image: postgres:14
    container_name: travel-agency-test-db
    env_file:
      - .env.test
    ports:
      - ${DB_PORT:-54321}:5432
    environment:
      - POSTGRES_SERVER=test-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test-db

  travel-agency-api:
    build:
      context: .
    depends_on:
      - travel-agency-db
    container_name: travel-agency-api
    env_file:
      - .env
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./:/code/
volumes:
  travel-agency-db-data:
