name: Code Quality Checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.0"

      - name: Run Ruff - Format Check
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"

      - name: Run Ruff - Lint Check
        uses: chartboost/ruff-action@v1
        with:
          args: "check"
